name: async_tracker
description: >
  Tracks async callbacks (e.g. microtask, Future, Stream, Timer) and
  indicates when any of these has completed their execution chain.
version: 0.1.3
homepage: https://github.com/isoos/async_tracker
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
