name: async_tracker
description: >
  Tracks async callbacks (e.g. microtask, Future, Stream, Timer) and
  indicates when any of these has completed their execution chain.
version: 0.1.4
homepage: https://github.com/isoos/async_tracker

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
